name: lesson_09
description: Dart.Isolates (lesson 09)
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  stream_channel: ^2.0.0
  json_annotation: ^3.0.1
  http: ^0.12.2
  isolate: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: ^3.4.1

flutter:
  uses-material-design: true